//! Live Oracle integration test, ignored by default.
//!
//! Enable with the `RUSTGRID_ORACLE_*` environment variables and:
//!
//! ```text
//! cargo test -p rustgrid-oracle -- --ignored
//! ```
//!
//! Defaults: host `localhost`, port `1521`, user `system`, service `FREEPDB1`
//! (`docker run -d --name rg-oracle -p 1521:1521 -e ORACLE_PASSWORD=oracle gvenzl/oracle-free:23-slim`).

use std::collections::BTreeMap;

use rustgrid_core::{
    ConnectionConfig, ConnectionOptions, Driver, DriverDialect, DriverId, RowInsert, RowUpdate,
};
use rustgrid_oracle::OracleDriver;

fn env(key: &str, default: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| default.to_string())
}

fn config() -> ConnectionConfig {
    ConnectionConfig {
        driver: DriverId::new("oracle"),
        host: env("RUSTGRID_ORACLE_HOST", "localhost"),
        port: env("RUSTGRID_ORACLE_PORT", "1521").parse().unwrap_or(1521),
        username: env("RUSTGRID_ORACLE_USER", "system"),
        password: std::env::var("RUSTGRID_ORACLE_PASSWORD").ok(),
        database: Some(env("RUSTGRID_ORACLE_SERVICE", "FREEPDB1")),
        options: BTreeMap::new(),
        settings: ConnectionOptions::default(),
    }
}

#[test]
fn driver_metadata() {
    let driver = OracleDriver::new();
    assert_eq!(driver.id(), DriverId::new("oracle"));
    assert_eq!(driver.default_port(), 1521);
    assert_eq!(driver.dialect(), DriverDialect::Oracle);
    assert!(driver.supports_schemas());
    assert!(driver.supports_users());
    assert!(!driver.supports_database_management());
}

#[test]
#[ignore = "requires a live Oracle server (RUSTGRID_ORACLE_PASSWORD)"]
fn connects_and_browses() {
    let runtime = tokio::runtime::Runtime::new().unwrap();
    runtime.block_on(async {
        let driver = OracleDriver::new();
        let connection = driver.connect(&config()).await.expect("connect");

        let databases = connection.list_databases().await.expect("databases");
        assert!(!databases.is_empty());

        let schemas = connection.list_schemas("").await.expect("schemas");
        assert!(!schemas.iter().any(|schema| schema == "SYS"));

        let version = connection.server_version().await.expect("version");
        assert!(!version.is_empty());

        // Arbitrary SQL, including a statement that ends with a semicolon and a PL/SQL block.
        connection
            .execute_query(None, "SELECT 1 FROM dual;")
            .await
            .expect("trailing semicolon is accepted");

        let results = connection
            .execute_query_many(None, "BEGIN NULL; END;")
            .await
            .expect("PL/SQL block runs");
        assert!(results.is_empty() || results.iter().all(|result| !result.has_result_set));

        connection.close().await.expect("close");
    });
}

#[test]
#[ignore = "requires a live Oracle server (RUSTGRID_ORACLE_PASSWORD)"]
fn edits_a_table() {
    let runtime = tokio::runtime::Runtime::new().unwrap();
    runtime.block_on(async {
        let driver = OracleDriver::new();
        let connection = driver.connect(&config()).await.expect("connect");

        connection
            .execute_query(None, "DROP TABLE \"APP\".\"RG_T\"")
            .await
            .ok();
        connection
            .execute_query(
                None,
                "CREATE TABLE \"APP\".\"RG_T\" (\
                   \"ID\" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
                   \"NAME\" VARCHAR2(50), \"CREATED\" DATE)",
            )
            .await
            .expect("create table");

        let page = connection
            .fetch_page("", "APP.RG_T", rustgrid_core::PageRequest::new(0, 50))
            .await
            .expect("fetch");
        assert!(
            page.columns
                .iter()
                .any(|column| column.name == "ID" && column.primary_key)
        );

        connection
            .insert_rows(
                "",
                "APP.RG_T",
                &[RowInsert {
                    values: vec![
                        ("NAME".to_string(), Some("alpha".to_string())),
                        (
                            "CREATED".to_string(),
                            Some("2025-01-02 03:04:05".to_string()),
                        ),
                    ],
                }],
            )
            .await
            .expect("insert");

        connection
            .update_rows(
                "",
                "APP.RG_T",
                &[RowUpdate {
                    set: vec![("NAME".to_string(), Some("beta".to_string()))],
                    keys: vec![("NAME".to_string(), Some("alpha".to_string()))],
                }],
            )
            .await
            .expect("update");

        connection
            .delete_rows(
                "",
                "APP.RG_T",
                &[vec![("NAME".to_string(), Some("beta".to_string()))]],
            )
            .await
            .expect("delete");

        connection.drop_table("", "APP.RG_T").await.expect("drop");
    });
}
