[package]
name = "rustgrid-postgresql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rustgrid-core.workspace = true
rustgrid-tunnel.workspace = true
async-trait.workspace = true
chrono.workspace = true
futures-util.workspace = true
tokio.workspace = true
sqlx = { workspace = true, features = ["postgres"] }

[dev-dependencies]
tokio.workspace = true
