[package]
name = "rustgrid-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rustgrid-core.workspace = true
async-trait.workspace = true
sqlx = { workspace = true, features = ["sqlite"] }

[dev-dependencies]
tokio.workspace = true
