[package]
name = "rustgrid-tunnel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rustgrid-core.workspace = true
tokio.workspace = true
russh.workspace = true
base64.workspace = true
