[package]
name = "rustgrid-export"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rustgrid-core.workspace = true
rust_xlsxwriter.workspace = true
thiserror.workspace = true
