//! PostgreSQL table introspection and `CREATE`/`ALTER TABLE` generation for the table designer.

use std::collections::HashMap;

use rustgrid_core::{
    ColumnDef, ForeignKeyDef, IndexDef, Result, TableOptions, TableSchema, TriggerDef,
};
use sqlx::Row;

use crate::connection::{PostgresConnection, map_query_error};
use crate::helpers::{qualify, quote_identifier, quote_literal};

/// Split a `format_type` string (e.g. `character varying(50)`, `numeric(10,2)`,
/// `timestamp with time zone`) into a designer base type plus its length/decimals.
fn split_format_type(format_type: &str) -> (String, String, String) {
    let format_type = format_type.trim();
    if let Some(base) = format_type.strip_suffix("[]") {
        return (format!("{base}[]"), String::new(), String::new());
    }
    // Pull out an optional `(p[,s])` qualifier.
    let (head, qualifier) = match format_type.split_once('(') {
        Some((head, rest)) => (head.trim(), rest.trim_end_matches(')').trim().to_string()),
        None => (format_type, String::new()),
    };
    let (length, decimals) = match qualifier.split_once(',') {
        Some((first, second)) => (first.trim().to_string(), second.trim().to_string()),
        None => (qualifier, String::new()),
    };
    let base = match head {
        "character varying" => "varchar",
        "character" => "char",
        "timestamp with time zone" => "timestamptz",
        "timestamp without time zone" => "timestamp",
        "time with time zone" => "timetz",
        "time without time zone" => "time",
        other => other,
    };
    (base.to_string(), length, decimals)
}

/// Render one column definition for `CREATE`/`ALTER TABLE`.
fn column_sql(column: &ColumnDef) -> String {
    let mut sql = quote_identifier(&column.name);
    let data_type = if column.data_type.trim().is_empty() {
        "text"
    } else {
        column.data_type.trim()
    };
    sql.push(' ');
    sql.push_str(data_type);

    let serial = data_type.to_ascii_lowercase().ends_with("serial");
    let length = column.length.trim();
    let decimals = column.decimals.trim();
    if !length.is_empty() && length != "0" {
        sql.push('(');
        sql.push_str(length);
        if !decimals.is_empty() && decimals != "0" {
            sql.push(',');
            sql.push_str(decimals);
        }
        sql.push(')');
    }

    if !column.nullable {
        sql.push_str(" NOT NULL");
    }
    if !column.default.trim().is_empty() {
        sql.push_str(" DEFAULT ");
        sql.push_str(column.default.trim());
    }
    if column.auto_increment && !serial {
        sql.push_str(" GENERATED BY DEFAULT AS IDENTITY");
    }
    if !column.comment.trim().is_empty() {
        // Comments are emitted as separate `COMMENT ON COLUMN` statements by the caller.
    }
    sql
}

fn index_sql(schema: &str, table: &str, index: &IndexDef) -> String {
    let columns = index
        .columns
        .iter()
        .map(|column| quote_identifier(column))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "CREATE {}INDEX {} ON {} ({columns})",
        if index.unique { "UNIQUE " } else { "" },
        quote_identifier(&index.name),
        qualify(schema, table)
    )
}

fn foreign_key_sql(foreign_key: &ForeignKeyDef) -> String {
    let columns = foreign_key
        .columns
        .iter()
        .map(|column| quote_identifier(column))
        .collect::<Vec<_>>()
        .join(", ");
    let referenced = foreign_key
        .referenced_columns
        .iter()
        .map(|column| quote_identifier(column))
        .collect::<Vec<_>>()
        .join(", ");
    let referenced_table = if foreign_key.referenced_table.contains('.') {
        let (schema, name) = foreign_key
            .referenced_table
            .split_once('.')
            .expect("checked contains dot");
        qualify(schema, name)
    } else {
        quote_identifier(&foreign_key.referenced_table)
    };
    let mut sql = format!(
        "CONSTRAINT {} FOREIGN KEY ({columns}) REFERENCES {referenced_table} ({referenced})",
        quote_identifier(&foreign_key.name),
    );
    if !foreign_key.on_delete.trim().is_empty() {
        sql.push_str(" ON DELETE ");
        sql.push_str(foreign_key.on_delete.trim());
    }
    if !foreign_key.on_update.trim().is_empty() {
        sql.push_str(" ON UPDATE ");
        sql.push_str(foreign_key.on_update.trim());
    }
    sql
}

pub(crate) async fn table_schema(
    connection: &PostgresConnection,
    database: &str,
    table: &str,
) -> Result<TableSchema> {
    let (schema_name, bare) = connection.resolve_object(database, table).await?;
    let pool = connection.pool_for(database).await?;

    let column_rows = sqlx::query(
        "SELECT a.attname, \
                format_type(a.atttypid, a.atttypmod) AS data_type, \
                NOT a.attnotnull AS nullable, \
                pg_get_expr(d.adbin, d.adrelid) AS default_expr, \
                col_description(a.attrelid, a.attnum) AS comment, \
                a.attidentity, \
                EXISTS (SELECT 1 FROM pg_index i \
                        WHERE i.indrelid = a.attrelid AND i.indisprimary \
                          AND a.attnum = ANY(i.indkey)) AS primary_key \
         FROM pg_attribute a \
         JOIN pg_class c ON c.oid = a.attrelid \
         JOIN pg_namespace n ON n.oid = c.relnamespace \
         LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum \
         WHERE n.nspname = $1 AND c.relname = $2 \
           AND a.attnum > 0 AND NOT a.attisdropped \
         ORDER BY a.attnum",
    )
    .bind(&schema_name)
    .bind(&bare)
    .fetch_all(&pool)
    .await
    .map_err(map_query_error)?;

    let mut columns = Vec::with_capacity(column_rows.len());
    for row in &column_rows {
        let name: String = row.try_get(0).unwrap_or_default();
        let format_type: String = row.try_get(1).unwrap_or_default();
        let nullable: bool = row.try_get(2).unwrap_or(true);
        let default_expr: Option<String> = row.try_get(3).unwrap_or(None);
        let comment: String = row.try_get(4).unwrap_or(None).unwrap_or_default();
        let identity: String = row.try_get(5).unwrap_or_default();
        let primary_key: bool = row.try_get(6).unwrap_or(false);

        let (data_type, length, decimals) = split_format_type(&format_type);
        let default = default_expr.unwrap_or_default();
        let is_serial_default = default.to_ascii_lowercase().starts_with("nextval(");
        let auto_increment = !identity.is_empty() || is_serial_default;
        columns.push(ColumnDef {
            name,
            data_type,
            length,
            decimals,
            nullable,
            default: if is_serial_default {
                String::new()
            } else {
                default
            },
            primary_key,
            auto_increment,
            unsigned: false,
            zerofill: false,
            comment,
            charset: String::new(),
            collation: String::new(),
            extra: String::new(),
            generated: String::new(),
            stored: false,
        });
    }

    let index_rows = sqlx::query(
        "SELECT i.relname, ix.indisunique, ix.indisprimary, a.attname \
         FROM pg_index ix \
         JOIN pg_class i ON i.oid = ix.indexrelid \
         JOIN pg_class t ON t.oid = ix.indrelid \
         JOIN pg_namespace n ON n.oid = t.relnamespace \
         CROSS JOIN LATERAL unnest(ix.indkey) WITH ORDINALITY AS k(attnum, ord) \
         JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = k.attnum \
         WHERE n.nspname = $1 AND t.relname = $2 \
         ORDER BY i.relname, k.ord",
    )
    .bind(&schema_name)
    .bind(&bare)
    .fetch_all(&pool)
    .await
    .map_err(map_query_error)?;
    let mut indexes: Vec<IndexDef> = Vec::new();
    for row in &index_rows {
        let name: String = row.try_get(0).unwrap_or_default();
        let unique: bool = row.try_get(1).unwrap_or(false);
        let primary: bool = row.try_get(2).unwrap_or(false);
        let column: String = row.try_get(3).unwrap_or_default();
        match indexes.iter_mut().find(|index| index.name == name) {
            Some(existing) => existing.columns.push(column),
            None => indexes.push(IndexDef {
                name,
                columns: vec![column],
                unique,
                primary,
                index_type: String::new(),
                comment: String::new(),
            }),
        }
    }

    let fk_rows = sqlx::query(
        "SELECT con.conname, \
                (SELECT array_agg(a.attname ORDER BY k.ord) \
                 FROM unnest(con.conkey) WITH ORDINALITY AS k(attnum, ord) \
                 JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = k.attnum) AS columns, \
                rn.nspname, rc.relname, \
                (SELECT array_agg(a.attname ORDER BY k.ord) \
                 FROM unnest(con.confkey) WITH ORDINALITY AS k(attnum, ord) \
                 JOIN pg_attribute a ON a.attrelid = con.confrelid AND a.attnum = k.attnum) AS ref_columns, \
                con.confupdtype, con.confdeltype \
         FROM pg_constraint con \
         JOIN pg_class c ON c.oid = con.conrelid \
         JOIN pg_namespace n ON n.oid = c.relnamespace \
         JOIN pg_class rc ON rc.oid = con.confrelid \
         JOIN pg_namespace rn ON rn.oid = rc.relnamespace \
         WHERE n.nspname = $1 AND c.relname = $2 AND con.contype = 'f' \
         ORDER BY con.conname",
    )
    .bind(&schema_name)
    .bind(&bare)
    .fetch_all(&pool)
    .await
    .map_err(map_query_error)?;
    let mut foreign_keys = Vec::with_capacity(fk_rows.len());
    for row in &fk_rows {
        let name: String = row.try_get(0).unwrap_or_default();
        let columns: Vec<String> = row.try_get(1).unwrap_or_default();
        let ref_schema: String = row.try_get(2).unwrap_or_default();
        let ref_table: String = row.try_get(3).unwrap_or_default();
        let ref_columns: Vec<String> = row.try_get(4).unwrap_or_default();
        let update_type: String = row.try_get(5).unwrap_or_default();
        let delete_type: String = row.try_get(6).unwrap_or_default();
        foreign_keys.push(ForeignKeyDef {
            name,
            columns,
            referenced_table: format!("{ref_schema}.{ref_table}"),
            referenced_columns: ref_columns,
            on_delete: normalize_action(&delete_type),
            on_update: normalize_action(&update_type),
        });
    }

    let trigger_rows = sqlx::query(
        "SELECT t.tgname, pg_get_triggerdef(t.oid) \
         FROM pg_trigger t \
         JOIN pg_class c ON c.oid = t.tgrelid \
         JOIN pg_namespace n ON n.oid = c.relnamespace \
         WHERE n.nspname = $1 AND c.relname = $2 AND NOT t.tgisinternal \
         ORDER BY t.tgname",
    )
    .bind(&schema_name)
    .bind(&bare)
    .fetch_all(&pool)
    .await
    .map_err(map_query_error)?;
    let triggers = trigger_rows
        .iter()
        .map(|row| TriggerDef {
            name: row.try_get(0).unwrap_or_default(),
            timing: String::new(),
            event: String::new(),
            statement: row.try_get(1).unwrap_or_default(),
        })
        .collect();

    let comment = sqlx::query(
        "SELECT obj_description(c.oid, 'pg_class') \
         FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace \
         WHERE n.nspname = $1 AND c.relname = $2",
    )
    .bind(&schema_name)
    .bind(&bare)
    .fetch_optional(&pool)
    .await
    .map_err(map_query_error)?
    .and_then(|row| row.try_get::<String, _>(0).ok())
    .unwrap_or_default();

    Ok(TableSchema {
        columns,
        indexes,
        foreign_keys,
        triggers,
        options: TableOptions {
            comment,
            ..Default::default()
        },
    })
}

fn normalize_action(code: &str) -> String {
    match code {
        "c" => "CASCADE".to_string(),
        "n" => "SET NULL".to_string(),
        "d" => "SET DEFAULT".to_string(),
        "r" => "RESTRICT".to_string(),
        _ => String::new(),
    }
}

fn primary_columns(schema: &TableSchema) -> Vec<String> {
    schema
        .columns
        .iter()
        .filter(|column| column.primary_key)
        .map(|column| column.name.clone())
        .collect()
}

fn primary_index_name(schema: &TableSchema) -> Option<String> {
    schema
        .indexes
        .iter()
        .find(|index| index.primary)
        .map(|index| index.name.clone())
}

fn comment_statements(schema_name: &str, table: &str, schema: &TableSchema) -> Vec<String> {
    let mut statements = Vec::new();
    if !schema.options.comment.trim().is_empty() {
        statements.push(format!(
            "COMMENT ON TABLE {} IS {}",
            qualify(schema_name, table),
            quote_literal(schema.options.comment.trim())
        ));
    }
    for column in &schema.columns {
        if !column.comment.trim().is_empty() {
            statements.push(format!(
                "COMMENT ON COLUMN {}.{} IS {}",
                qualify(schema_name, table),
                quote_identifier(&column.name),
                quote_literal(column.comment.trim())
            ));
        }
    }
    statements
}

pub(crate) fn table_schema_sql(
    schema_name: &str,
    table: &str,
    original: Option<&TableSchema>,
    modified: &TableSchema,
) -> String {
    let qualified = qualify(schema_name, table);

    let Some(original) = original else {
        let mut definitions: Vec<String> = modified.columns.iter().map(column_sql).collect();
        let primary = primary_columns(modified);
        if !primary.is_empty() {
            definitions.push(format!(
                "PRIMARY KEY ({})",
                primary
                    .iter()
                    .map(|column| quote_identifier(column))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        for foreign_key in &modified.foreign_keys {
            definitions.push(foreign_key_sql(foreign_key));
        }
        let mut statements = vec![format!(
            "CREATE TABLE {qualified} (\n    {}\n)",
            definitions.join(",\n    ")
        )];
        for index in modified.indexes.iter().filter(|index| !index.primary) {
            statements.push(index_sql(schema_name, table, index));
        }
        statements.extend(comment_statements(schema_name, table, modified));
        return statements.join(";\n");
    };

    let mut statements: Vec<String> = Vec::new();
    let original_columns: HashMap<&str, &ColumnDef> = original
        .columns
        .iter()
        .map(|column| (column.name.as_str(), column))
        .collect();
    let modified_columns: HashMap<&str, &ColumnDef> = modified
        .columns
        .iter()
        .map(|column| (column.name.as_str(), column))
        .collect();

    for column in &modified.columns {
        match original_columns.get(column.name.as_str()) {
            None => statements.push(format!(
                "ALTER TABLE {qualified} ADD COLUMN {}",
                column_sql(column)
            )),
            Some(previous) => {
                let type_changed = previous.data_type != column.data_type
                    || previous.length != column.length
                    || previous.decimals != column.decimals;
                if type_changed {
                    statements.push(format!(
                        "ALTER TABLE {qualified} ALTER COLUMN {} TYPE {} USING {}::{}",
                        quote_identifier(&column.name),
                        column_type_sql(column),
                        quote_identifier(&column.name),
                        column_type_sql(column)
                    ));
                }
                if previous.nullable != column.nullable {
                    statements.push(format!(
                        "ALTER TABLE {qualified} ALTER COLUMN {} {} NOT NULL",
                        quote_identifier(&column.name),
                        if column.nullable { "DROP" } else { "SET" }
                    ));
                }
                if previous.default != column.default {
                    let clause = if column.default.trim().is_empty() {
                        "DROP DEFAULT".to_string()
                    } else {
                        format!("SET DEFAULT {}", column.default.trim())
                    };
                    statements.push(format!(
                        "ALTER TABLE {qualified} ALTER COLUMN {} {clause}",
                        quote_identifier(&column.name)
                    ));
                }
                if previous.auto_increment != column.auto_increment {
                    let clause = if column.auto_increment {
                        "ADD GENERATED BY DEFAULT AS IDENTITY"
                    } else {
                        "DROP IDENTITY IF EXISTS"
                    };
                    statements.push(format!(
                        "ALTER TABLE {qualified} ALTER COLUMN {} {clause}",
                        quote_identifier(&column.name)
                    ));
                }
                if previous.comment != column.comment {
                    statements.push(format!(
                        "COMMENT ON COLUMN {}.{} IS {}",
                        qualified,
                        quote_identifier(&column.name),
                        if column.comment.trim().is_empty() {
                            "NULL".to_string()
                        } else {
                            quote_literal(column.comment.trim())
                        }
                    ));
                }
            }
        }
    }
    for column in &original.columns {
        if !modified_columns.contains_key(column.name.as_str()) {
            statements.push(format!(
                "ALTER TABLE {qualified} DROP COLUMN {}",
                quote_identifier(&column.name)
            ));
        }
    }

    let original_primary = primary_columns(original);
    let modified_primary = primary_columns(modified);
    if original_primary != modified_primary {
        if let Some(name) = primary_index_name(original) {
            statements.push(format!(
                "ALTER TABLE {qualified} DROP CONSTRAINT {}",
                quote_identifier(&name)
            ));
        }
        if !modified_primary.is_empty() {
            statements.push(format!(
                "ALTER TABLE {qualified} ADD PRIMARY KEY ({})",
                modified_primary
                    .iter()
                    .map(|column| quote_identifier(column))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
    }

    let original_indexes: HashMap<&str, &IndexDef> = original
        .indexes
        .iter()
        .map(|index| (index.name.as_str(), index))
        .collect();
    let modified_indexes: HashMap<&str, &IndexDef> = modified
        .indexes
        .iter()
        .map(|index| (index.name.as_str(), index))
        .collect();
    for index in modified.indexes.iter().filter(|index| !index.primary) {
        if !original_indexes.contains_key(index.name.as_str()) {
            statements.push(index_sql(schema_name, table, index));
        }
    }
    for index in original.indexes.iter().filter(|index| !index.primary) {
        if !modified_indexes.contains_key(index.name.as_str()) {
            statements.push(format!("DROP INDEX {}", qualify(schema_name, &index.name)));
        }
    }

    let original_fks: HashMap<&str, &ForeignKeyDef> = original
        .foreign_keys
        .iter()
        .map(|foreign_key| (foreign_key.name.as_str(), foreign_key))
        .collect();
    let modified_fks: HashMap<&str, &ForeignKeyDef> = modified
        .foreign_keys
        .iter()
        .map(|foreign_key| (foreign_key.name.as_str(), foreign_key))
        .collect();
    for foreign_key in &modified.foreign_keys {
        match original_fks.get(foreign_key.name.as_str()) {
            None => statements.push(format!(
                "ALTER TABLE {qualified} ADD {}",
                foreign_key_sql(foreign_key)
            )),
            Some(existing) if *existing != foreign_key => {
                statements.push(format!(
                    "ALTER TABLE {qualified} DROP CONSTRAINT {}",
                    quote_identifier(&foreign_key.name)
                ));
                statements.push(format!(
                    "ALTER TABLE {qualified} ADD {}",
                    foreign_key_sql(foreign_key)
                ));
            }
            Some(_) => {}
        }
    }
    for foreign_key in &original.foreign_keys {
        if !modified_fks.contains_key(foreign_key.name.as_str()) {
            statements.push(format!(
                "ALTER TABLE {qualified} DROP CONSTRAINT {}",
                quote_identifier(&foreign_key.name)
            ));
        }
    }

    if original.options.comment != modified.options.comment {
        statements.push(format!(
            "COMMENT ON TABLE {qualified} IS {}",
            if modified.options.comment.trim().is_empty() {
                "NULL".to_string()
            } else {
                quote_literal(modified.options.comment.trim())
            }
        ));
    }

    statements.join(";\n")
}

/// The SQL type of a column (base type plus its qualifier), for `ALTER COLUMN ... TYPE`.
fn column_type_sql(column: &ColumnDef) -> String {
    let mut sql = column.data_type.trim().to_string();
    let length = column.length.trim();
    let decimals = column.decimals.trim();
    if !length.is_empty() && length != "0" {
        sql.push('(');
        sql.push_str(length);
        if !decimals.is_empty() && decimals != "0" {
            sql.push(',');
            sql.push_str(decimals);
        }
        sql.push(')');
    }
    sql
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splits_format_types() {
        assert_eq!(
            split_format_type("character varying(50)"),
            ("varchar".to_string(), "50".to_string(), String::new())
        );
        assert_eq!(
            split_format_type("numeric(10,2)"),
            ("numeric".to_string(), "10".to_string(), "2".to_string())
        );
        assert_eq!(
            split_format_type("timestamp with time zone"),
            ("timestamptz".to_string(), String::new(), String::new())
        );
        assert_eq!(
            split_format_type("integer[]"),
            ("integer[]".to_string(), String::new(), String::new())
        );
    }

    #[test]
    fn builds_create_table() {
        let schema = TableSchema {
            columns: vec![ColumnDef {
                name: "id".to_string(),
                data_type: "integer".to_string(),
                nullable: false,
                primary_key: true,
                auto_increment: true,
                ..Default::default()
            }],
            ..Default::default()
        };
        let sql = table_schema_sql("public", "t", None, &schema);
        assert!(sql.starts_with("CREATE TABLE \"public\".\"t\""));
        assert!(sql.contains("\"id\" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY"));
        assert!(sql.contains("PRIMARY KEY (\"id\")"));
    }
}
