use gpui::WindowAppearance;
use navidog_config::ThemeSetting;

#[derive(Clone, Copy, PartialEq, Eq)]
pub struct Theme {
    pub window_bg: u32,
    pub titlebar_bg: u32,
    pub sidebar_bg: u32,
    pub editor_bg: u32,
    pub toolbar_bg: u32,
    pub header_bg: u32,
    pub row_alt_bg: u32,
    pub cell_edit_bg: u32,
    pub grid_selection_bg: u32,
    pub grid_selection_text: u32,
    pub dialog_bg: u32,
    pub dialog_face: u32,
    pub input_bg: u32,
    pub border: u32,
    pub grid_line: u32,
    pub text: u32,
    pub text_muted: u32,
    pub text_null: u32,
    pub button_bg: u32,
    pub button_hover_bg: u32,
    pub button_border: u32,
    pub button_default_border: u32,
    pub primary: u32,
    pub overlay: u32,
    pub tree_hover_bg: u32,
    pub tree_selected_bg: u32,
    pub tree_selected_text: u32,
    pub chevron: u32,
    pub icon_connection: u32,
    pub icon_database: u32,
    pub icon_database_active: u32,
    pub icon_tables: u32,
    pub icon_views: u32,
    pub icon_functions: u32,
    pub icon_queries: u32,
    pub icon_backups: u32,
    pub icon_table: u32,
    pub icon_view: u32,
    pub warning: u32,
    pub danger: u32,
    pub neutral: u32,
    pub sql_keyword: u32,
    pub sql_string: u32,
    pub sql_number: u32,
    pub sql_comment: u32,
}

impl Theme {
    /// The light palette, aligned with shadcn/ui's default ("zinc") design tokens.
    pub const fn light() -> Self {
        Self {
            window_bg: 0xffffff,
            titlebar_bg: 0xfafafa,
            sidebar_bg: 0xfafafa,
            editor_bg: 0xffffff,
            toolbar_bg: 0xfafafa,
            header_bg: 0xf4f4f5,
            row_alt_bg: 0xfafafa,
            cell_edit_bg: 0xfef9c3,
            grid_selection_bg: 0x3b82f6,
            grid_selection_text: 0xffffff,
            dialog_bg: 0xffffff,
            dialog_face: 0xfafafa,
            input_bg: 0xffffff,
            border: 0xe4e4e7,
            grid_line: 0xf1f1f3,
            text: 0x09090b,
            text_muted: 0x71717a,
            text_null: 0xa1a1aa,
            button_bg: 0xf4f4f5,
            button_hover_bg: 0xe4e4e7,
            button_border: 0xe4e4e7,
            button_default_border: 0xa1a1aa,
            primary: 0x18181b,
            overlay: 0x0000004d,
            tree_hover_bg: 0xf4f4f5,
            tree_selected_bg: 0xf4f4f5,
            tree_selected_text: 0x09090b,
            chevron: 0x71717a,
            icon_connection: 0x16a34a,
            icon_database: 0x71717a,
            icon_database_active: 0x16a34a,
            icon_tables: 0x16a34a,
            icon_views: 0x3b82f6,
            icon_functions: 0xd97706,
            icon_queries: 0x0d9488,
            icon_backups: 0xca8a04,
            icon_table: 0x3b82f6,
            icon_view: 0x3b82f6,
            warning: 0xd97706,
            danger: 0xef4444,
            neutral: 0xa1a1aa,
            sql_keyword: 0x8250df,
            sql_string: 0x0a7d33,
            sql_number: 0x0550ae,
            sql_comment: 0x8b949e,
        }
    }

    /// The dark palette, aligned with shadcn/ui's default ("zinc") design tokens.
    pub const fn dark() -> Self {
        Self {
            window_bg: 0x09090b,
            titlebar_bg: 0x09090b,
            sidebar_bg: 0x09090b,
            editor_bg: 0x09090b,
            toolbar_bg: 0x09090b,
            header_bg: 0x18181b,
            row_alt_bg: 0x0c0c0e,
            cell_edit_bg: 0x3f3f46,
            grid_selection_bg: 0x2563eb,
            grid_selection_text: 0xfafafa,
            dialog_bg: 0x09090b,
            dialog_face: 0x18181b,
            input_bg: 0x09090b,
            border: 0x27272a,
            grid_line: 0x1c1c1f,
            text: 0xfafafa,
            text_muted: 0xa1a1aa,
            text_null: 0x52525b,
            button_bg: 0x27272a,
            button_hover_bg: 0x3f3f46,
            button_border: 0x27272a,
            button_default_border: 0xd4d4d8,
            primary: 0xfafafa,
            overlay: 0x000000a6,
            tree_hover_bg: 0x18181b,
            tree_selected_bg: 0x27272a,
            tree_selected_text: 0xfafafa,
            chevron: 0xa1a1aa,
            icon_connection: 0x4ade80,
            icon_database: 0xa1a1aa,
            icon_database_active: 0x4ade80,
            icon_tables: 0x4ade80,
            icon_views: 0x60a5fa,
            icon_functions: 0xfbbf24,
            icon_queries: 0x2dd4bf,
            icon_backups: 0xfacc15,
            icon_table: 0x60a5fa,
            icon_view: 0x60a5fa,
            warning: 0xfbbf24,
            danger: 0xef4444,
            neutral: 0x52525b,
            sql_keyword: 0xc4b5fd,
            sql_string: 0x7ee787,
            sql_number: 0x79c0ff,
            sql_comment: 0x8b949e,
        }
    }

    pub fn resolve(setting: ThemeSetting, appearance: WindowAppearance) -> Self {
        match setting {
            ThemeSetting::Light => Self::light(),
            ThemeSetting::Dark => Self::dark(),
            ThemeSetting::System => match appearance {
                WindowAppearance::Light | WindowAppearance::VibrantLight => Self::light(),
                WindowAppearance::Dark | WindowAppearance::VibrantDark => Self::dark(),
            },
        }
    }

    /// Whether this palette is the dark one, used to keep gpui-kit's theme in lockstep.
    pub fn is_dark(&self) -> bool {
        self.window_bg == Self::dark().window_bg
    }
}
