use gpui::WindowAppearance;
use navidog_config::ThemeSetting;

#[derive(Clone, Copy)]
pub struct Theme {
    pub window_bg: u32,
    pub titlebar_bg: u32,
    pub sidebar_bg: u32,
    pub editor_bg: u32,
    pub toolbar_bg: u32,
    pub header_bg: u32,
    pub row_alt_bg: u32,
    pub cell_edit_bg: u32,
    pub dialog_bg: u32,
    pub dialog_face: u32,
    pub input_bg: u32,
    pub border: u32,
    pub text: u32,
    pub text_muted: u32,
    pub button_bg: u32,
    pub button_hover_bg: u32,
    pub button_border: u32,
    pub button_default_border: u32,
    pub primary: u32,
    pub overlay: u32,
    pub tree_hover_bg: u32,
    pub tree_selected_bg: u32,
    pub tree_selected_text: u32,
    pub chevron: u32,
    pub icon_connection: u32,
    pub icon_database: u32,
    pub icon_database_active: u32,
    pub icon_tables: u32,
    pub icon_views: u32,
    pub icon_functions: u32,
    pub icon_queries: u32,
    pub icon_backups: u32,
    pub icon_table: u32,
    pub icon_view: u32,
    pub warning: u32,
    pub danger: u32,
    pub neutral: u32,
}

impl Theme {
    pub const fn light() -> Self {
        Self {
            window_bg: 0xffffff,
            titlebar_bg: 0xf3f3f3,
            sidebar_bg: 0xffffff,
            editor_bg: 0xffffff,
            toolbar_bg: 0xf3f3f3,
            header_bg: 0xe8e8e8,
            row_alt_bg: 0xf7f7f7,
            cell_edit_bg: 0xffe9a8,
            dialog_bg: 0xffffff,
            dialog_face: 0xf0f0f0,
            input_bg: 0xffffff,
            border: 0xd9d9d9,
            text: 0x1f1f1f,
            text_muted: 0x6b6b6b,
            button_bg: 0xe6e6e6,
            button_hover_bg: 0xd6d6d6,
            button_border: 0xadadad,
            button_default_border: 0x0078d7,
            primary: 0x0e639c,
            overlay: 0x00000033,
            tree_hover_bg: 0xe8f0fe,
            tree_selected_bg: 0xcfe4fb,
            tree_selected_text: 0x000000,
            chevron: 0x707070,
            icon_connection: 0x2e9e5b,
            icon_database: 0x7c7c7c,
            icon_database_active: 0x2e9e5b,
            icon_tables: 0x2e9e5b,
            icon_views: 0x2a7fd4,
            icon_functions: 0xc07a00,
            icon_queries: 0x1f9e8f,
            icon_backups: 0xb08a00,
            icon_table: 0x2a7fd4,
            icon_view: 0x2a7fd4,
            warning: 0xb58900,
            danger: 0xd13438,
            neutral: 0x9a9a9a,
        }
    }

    pub const fn dark() -> Self {
        Self {
            window_bg: 0x1e1e1e,
            titlebar_bg: 0x323233,
            sidebar_bg: 0x252526,
            editor_bg: 0x1e1e1e,
            toolbar_bg: 0x252526,
            header_bg: 0x2d2d30,
            row_alt_bg: 0x232324,
            cell_edit_bg: 0x5c4a1e,
            dialog_bg: 0x2d2d30,
            dialog_face: 0x252526,
            input_bg: 0x1e1e1e,
            border: 0x3c3c3c,
            text: 0xd4d4d4,
            text_muted: 0x8a8a8a,
            button_bg: 0x3a3d41,
            button_hover_bg: 0x4a4d52,
            button_border: 0x555555,
            button_default_border: 0x4cc2ff,
            primary: 0x0e639c,
            overlay: 0x00000099,
            tree_hover_bg: 0x2a2d2e,
            tree_selected_bg: 0x094771,
            tree_selected_text: 0xffffff,
            chevron: 0x9a9a9a,
            icon_connection: 0x4ec9b0,
            icon_database: 0x9a9a9a,
            icon_database_active: 0x4ec9b0,
            icon_tables: 0x4ec9b0,
            icon_views: 0x4d9fe0,
            icon_functions: 0xd8a84a,
            icon_queries: 0x4fc1b0,
            icon_backups: 0xd8c06a,
            icon_table: 0x4d9fe0,
            icon_view: 0x4d9fe0,
            warning: 0xdcdcaa,
            danger: 0xf14c4c,
            neutral: 0x808080,
        }
    }

    pub fn resolve(setting: ThemeSetting, appearance: WindowAppearance) -> Self {
        match setting {
            ThemeSetting::Light => Self::light(),
            ThemeSetting::Dark => Self::dark(),
            ThemeSetting::System => match appearance {
                WindowAppearance::Light | WindowAppearance::VibrantLight => Self::light(),
                WindowAppearance::Dark | WindowAppearance::VibrantDark => Self::dark(),
            },
        }
    }
}
