[package]
name = "rustgrid-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "RustGrid"
path = "src/main.rs"

[dependencies]
rustgrid-core.workspace = true
rustgrid-mysql.workspace = true
rustgrid-config.workspace = true
gpui.workspace = true
gpui-kit.workspace = true
rust-i18n.workspace = true
sqlparser.workspace = true
sqlformat.workspace = true
chrono.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
embed-resource.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle.workspace = true
windows.workspace = true
