[package]
name = "navidog-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "navidog"
path = "src/main.rs"

[dependencies]
navidog-core.workspace = true
navidog-mysql.workspace = true
navidog-config.workspace = true
gpui.workspace = true
rust-i18n.workspace = true
chrono.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle.workspace = true
windows.workspace = true
